# Generated by Django 4.0.3 on 2022-03-08 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('details', models.CharField(max_length=200)),
                ('approved', models.BooleanField()),
                ('public', models.BooleanField()),
                ('zipcode', models.IntegerField()),
                ('comments', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.PositiveBigIntegerField()),
                ('menu', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('public', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('about', models.TextField()),
                ('parentportal', models.BooleanField()),
                ('rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipzode', models.IntegerField()),
                ('parent', models.BooleanField()),
                ('details', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.community')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socioapi.member')),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=150)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='socioapi.member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.member')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.community')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField()),
                ('approved', models.BooleanField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.community')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.member')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('approved', models.BooleanField()),
                ('public', models.BooleanField()),
                ('details', models.CharField(max_length=250)),
                ('isactivity', models.BooleanField()),
                ('zipcode', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendees', models.ManyToManyField(related_name='attending', through='socioapi.AttendEvent', to='socioapi.member')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.community')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socioapi.member')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socioapi.member'),
        ),
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='socioapi.CommunityTag', to='socioapi.tag'),
        ),
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250)),
                ('approved', models.BooleanField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250)),
                ('approved', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.member'),
        ),
        migrations.AddField(
            model_name='attendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.communityevent'),
        ),
        migrations.AddField(
            model_name='attendevent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.member'),
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.announcement')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socioapi.member')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socioapi.community'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socioapi.member'),
        ),
    ]
