# Generated by Django 4.0.3 on 2022-03-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socioapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='zipzode',
            new_name='zipcode',
        ),
    ]
