# Generated by Django 4.0.3 on 2022-03-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioapi', '0003_businessevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
