# Generated by Django 4.0.3 on 2022-03-09 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socioapi', '0004_business_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
