# Generated by Django 4.0.3 on 2022-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioapi', '0005_communityevent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcomment',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
