# Generated by Django 4.0.3 on 2022-03-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socioapi', '0007_business_image_businessannouncement_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='socioapi.community'),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thecomments', to='socioapi.announcement'),
        ),
        migrations.AlterField(
            model_name='attendevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendingevent', to='socioapi.communityevent'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='socioapi.community'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='socioapi.community'),
        ),
    ]
