# Generated by Django 4.0.3 on 2022-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioapi', '0008_alter_announcement_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='read',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
