# Generated by Django 4.0.3 on 2022-03-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioapi', '0009_directmessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcementimages'),
        ),
        migrations.AlterField(
            model_name='announcementcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcementcommentimages'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='businessimages'),
        ),
        migrations.AlterField(
            model_name='businessannouncement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='businessannouncementimages'),
        ),
        migrations.AlterField(
            model_name='businessevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='businesseventimages'),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='communityimages'),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eventimages'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messageimages'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memberimages'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messageboardimages'),
        ),
    ]
